### ISSUE TITLE
缺少Config.h文件

### ISSUE THREAD

**Issue by sany620** [Coding/Coding-iPad#1]
缺少Config.h文件

**Comment by WangHengHeng** [comment]
![image](https://cloud.githubusercontent.com/assets/7866087/10752206/0f01f240-7cc2-11e5-8ab9-02859537a150.png)
运行项目前看下 readme 吧，[Coding-iOS](https://github.com/Coding/Coding-iOS) 的处理也是类似的。

**Comment by bluishoul** [comment]
@WangHengHeng 可以 close 掉这个 issue 了
